name: Baixar RPE 2024

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: python download.py

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: RPE_2024
          path: "*.zip"